# Development Environment
version: "3"

services:

# Jupyter Development Server
  notebook:
    build: .
    volumes:
      - .:/home/jovyan/work
    ports:
      - 8888:8888
    environment:
      - VM_URL=victoria_metrics:8428
    depends_on:
      - victoria_metrics
    links:
      - victoria_metrics
    container_name: notebooks

  victoria_metrics:
    container_name: victoria_metrics
    image: victoriametrics/victoria-metrics:latest
    command: -storageDataPath=/victoria-metrics-data -memory.allowedPercent=20
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - 8428:8428
      - 8089:8089
      - 8089:8089/udp
      - 2003:2003
      - 2003:2003/udp
      - 4242:4242
    volumes:
      - vmdata:/victoria-metrics-data

volumes:
   vmdata: {}